WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
TOPBAR_VERTICAL_OFFSET = WINDOW_HEIGHT - 25
LIVES_VERTICAL_OFFSET = WINDOW_HEIGHT - 15
LIVES_HORIZONTAL_OFFSET = WINDOW_WIDTH - 15
WINDOW_HORIZONTAL_CENTER = WINDOW_WIDTH / 2
WINDOW_VERTICAL_CENTER = WINDOW_HEIGHT / 2
